# Workflow para ejecutar pruebas e2e con WebdriverIO

name: E2E Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  e2e-tests:
    # Changed runner from ubuntu-latest to windows-latest
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-outs your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      # Instala Allure Command Line
      - name: Install Allure Command Line
        run: npm install -g allure-commandline
          
      # Instala dependencias
      - name: Install dependencies
        working-directory: ./shoopingCart
        run: npm install
      
      # Limpia reportes de Allure anteriores
      - name: Clean Allure reports
        working-directory: ./shoopingCart
        run: npm run allure:clean
        
      # Ejecuta las pruebas e2e
      - name: Run e2e tests
        working-directory: ./shoopingCart
        run: npm run e2e
        
      # Genera reportes de Allure
      - name: Generate Allure reports
        working-directory: ./shoopingCart
        run: npm run allure:generate
        
      # Guarda los reportes como artefactos
      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./shoopingCart/allure-report
          retention-days: 7
                # Guarda los screenshots como artefactos
    
      - name: Archive screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: ./shoopingCart/screenshots/**
          retention-days: 7